version: '3.7'

services:
  app:
    container_name: adm_videos_app
    build: .
#    image: deploydesexta/fc3-admin-catalogo-de-videos-java:modulos_29_ci-cd-2
    profiles: ["dev"]
    restart: unless-stopped
#    environment:
#      SPRING_PROFILES_ACTIVE: 'dev'
    ports:
      - "8080:8080"